// Autogenerated from Pigeon (v26.1.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsTryKmp(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsTryKmp(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsTryKmp(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashTryKmp(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashTryKmp(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashTryKmp(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct GitHubRepoDto: Hashable {
  var totalCount: Int64
  var incompleteResults: Bool
  var items: [GitHubRepoItemDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GitHubRepoDto? {
    let totalCount = pigeonVar_list[0] as! Int64
    let incompleteResults = pigeonVar_list[1] as! Bool
    let items = pigeonVar_list[2] as! [GitHubRepoItemDto]

    return GitHubRepoDto(
      totalCount: totalCount,
      incompleteResults: incompleteResults,
      items: items
    )
  }
  func toList() -> [Any?] {
    return [
      totalCount,
      incompleteResults,
      items,
    ]
  }
  static func == (lhs: GitHubRepoDto, rhs: GitHubRepoDto) -> Bool {
    return deepEqualsTryKmp(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashTryKmp(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GitHubRepoItemDto: Hashable {
  var fullName: String
  var description: String? = nil
  var url: String
  var updatedAt: String
  var language: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GitHubRepoItemDto? {
    let fullName = pigeonVar_list[0] as! String
    let description: String? = nilOrValue(pigeonVar_list[1])
    let url = pigeonVar_list[2] as! String
    let updatedAt = pigeonVar_list[3] as! String
    let language: String? = nilOrValue(pigeonVar_list[4])

    return GitHubRepoItemDto(
      fullName: fullName,
      description: description,
      url: url,
      updatedAt: updatedAt,
      language: language
    )
  }
  func toList() -> [Any?] {
    return [
      fullName,
      description,
      url,
      updatedAt,
      language,
    ]
  }
  static func == (lhs: GitHubRepoItemDto, rhs: GitHubRepoItemDto) -> Bool {
    return deepEqualsTryKmp(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashTryKmp(value: toList(), hasher: &hasher)
  }
}

private class TryKmpPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return GitHubRepoDto.fromList(self.readValue() as! [Any?])
    case 130:
      return GitHubRepoItemDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class TryKmpPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GitHubRepoDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? GitHubRepoItemDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TryKmpPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TryKmpPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TryKmpPigeonCodecWriter(data: data)
  }
}

class TryKmpPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TryKmpPigeonCodec(readerWriter: TryKmpPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TryKmpHostApi {
  func time() throws -> String
  func searchGitHubRepo(query: String) throws -> GitHubRepoDto
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TryKmpHostApiSetup {
  static var codec: FlutterStandardMessageCodec { TryKmpPigeonCodec.shared }
  /// Sets up an instance of `TryKmpHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TryKmpHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    let timeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.trykmp.TryKmpHostApi.time\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      timeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.time()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      timeChannel.setMessageHandler(nil)
    }
    let searchGitHubRepoChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.trykmp.TryKmpHostApi.searchGitHubRepo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.trykmp.TryKmpHostApi.searchGitHubRepo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      searchGitHubRepoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let queryArg = args[0] as! String
        do {
          let result = try api.searchGitHubRepo(query: queryArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      searchGitHubRepoChannel.setMessageHandler(nil)
    }
  }
}
