// Autogenerated from Pigeon (v26.1.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.tshion.try_flutter_plugin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object TryKmpPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class GitHubRepoDto (
  val totalCount: Long,
  val incompleteResults: Boolean,
  val items: List<GitHubRepoItemDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GitHubRepoDto {
      val totalCount = pigeonVar_list[0] as Long
      val incompleteResults = pigeonVar_list[1] as Boolean
      val items = pigeonVar_list[2] as List<GitHubRepoItemDto>
      return GitHubRepoDto(totalCount, incompleteResults, items)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalCount,
      incompleteResults,
      items,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is GitHubRepoDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return TryKmpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GitHubRepoItemDto (
  val fullName: String,
  val description: String? = null,
  val url: String,
  val updatedAt: String,
  val language: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GitHubRepoItemDto {
      val fullName = pigeonVar_list[0] as String
      val description = pigeonVar_list[1] as String?
      val url = pigeonVar_list[2] as String
      val updatedAt = pigeonVar_list[3] as String
      val language = pigeonVar_list[4] as String?
      return GitHubRepoItemDto(fullName, description, url, updatedAt, language)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fullName,
      description,
      url,
      updatedAt,
      language,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is GitHubRepoItemDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return TryKmpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class TryKmpPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GitHubRepoDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GitHubRepoItemDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GitHubRepoDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is GitHubRepoItemDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TryKmpHostApi {
  fun time(): String
  fun searchGitHubRepo(query: String, callback: (Result<GitHubRepoDto>) -> Unit)

  companion object {
    /** The codec used by TryKmpHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TryKmpPigeonCodec()
    }
    /** Sets up an instance of `TryKmpHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TryKmpHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trykmp.TryKmpHostApi.time$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.time())
            } catch (exception: Throwable) {
              TryKmpPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trykmp.TryKmpHostApi.searchGitHubRepo$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            api.searchGitHubRepo(queryArg) { result: Result<GitHubRepoDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TryKmpPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TryKmpPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
